In [1]:
import numpy as np
import scipy
import math
from scipy.optimize import minimize

In [2]:
HCondorTorres = np.array( [-25.482016244043514, -49.22050413069292])
SNiloPecanha =np.array([-25.41169572061714, -49.27377846003732])
SCondorAguaVerde =np.array( [-25.452411534381085, -49.27994254097753])
HCondorNovoMundo = np.array( [-25.48587331143218, -49.29593190236248])
HCondorSãoBraz = np.array( [-25.42171285405071, -49.349218246547])
HCondorPinheirinho = np.array( [-25.51547589450823, -49.29616495075367])
HCondorChampagnat = np.array( [-25.435121427978725, -49.303787446546714])
SCondorWenceslauBraz = np.array( [-25.47153181758941, -49.2626573851601])
HCondorSantaCandida = np.array( [-25.37724548690511, -49.22264971771121])
SCcondorMarechal =np.array( [-25.49219706615689, -49.24237338887239])
SCondorFranciscoDerosso = np.array( [-25.516661436988958, -49.256264844688744])
SCondorCampoComprido = np.array( [-25.46098937457784, -49.346204967878755])
SCondorJoãoBettega = np.array( [-25.492625124119012, -49.32437228701594])
SCondorSitioCercado = np.array( [-25.534019970221706, -49.26585744840101])
CEPostoIpiranga = np.array( [-25.43437867202696, -49.30937239097784])
SCondorBoaVista = np.array( [-25.387962578738392, -49.24428461585488])
SCondorCristoRei = np.array([-25.434306915402964, -49.24529939815508])
SCondorAvenidaBrasilia = np.array([-25.495704639288387, -49.27673006003559])
SCondorCajuru = np.array( [-25.45352050948544, -49.209102702363296])
SCondorSantaQuitéria = np.array( [-25.46036443625162, -49.32396247167011])
SCondorUmbará = np.array([-25.540842415249767, -49.2947628005052])
CondorGourmetAhú = np.array( [-25.396902536232016, -49.25708978330538])
SCondorSantaFelicidade = np.array( [-25.39468014283869, -49.34822601399845]) 
SCondorPilarzinho = np.array( [-25.38858020145726, -49.282953558181696])
CacauShowCondorBomRetiro = np.array( [-25.41180063128769, -49.27363597352748])

CD = np.array([-25.54960180883994, -49.28392552934169])


In [63]:
HCondorTorres = [-25.482016244043514, -49.22050413069292]
SNiloPecanha = [-25.41169572061714, -49.27377846003732]
SCondorAguaVerde = [-25.452411534381085, -49.27994254097753]
HCondorNovoMundo = [-25.48587331143218, -49.29593190236248]
HCondorSãoBraz = [-25.42171285405071, -49.349218246547]
HCondorPinheirinho = [-25.51547589450823, -49.29616495075367]
HCondorChampagnat = [-25.435121427978725, -49.303787446546714]
SCondorWenceslauBraz = [-25.47153181758941, -49.2626573851601]
HCondorSantaCandida = [-25.37724548690511, -49.22264971771121]
SCcondorMarechal = [-25.49219706615689, -49.24237338887239]
SCondorFranciscoDerosso = [-25.516661436988958, -49.256264844688744]
SCondorCampoComprido = [-25.46098937457784, -49.346204967878755]
SCondorJoãoBettega = [-25.492625124119012, -49.32437228701594]
SCondorSitioCercado = [-25.534019970221706, -49.26585744840101]
CEPostoIpiranga = [-25.43437867202696, -49.30937239097784]
SCondorBoaVista = [-25.387962578738392, -49.24428461585488]
SCondorCristoRei = [-25.434306915402964, -49.24529939815508]
SCondorAvenidaBrasilia = [-25.495704639288387, -49.27673006003559]
SCondorCajuru = [-25.45352050948544, -49.209102702363296]
SCondorSantaQuitéria = [-25.46036443625162, -49.32396247167011]
SCondorUmbará = [-25.540842415249767, -49.2947628005052]
CondorGourmetAhú = [-25.396902536232016, -49.25708978330538]
SCondorSantaFelicidade = [-25.39468014283869, -49.34822601399845]
SCondorPilarzinho = [-25.38858020145726, -49.282953558181696]
CacauShowCondorBomRetiro = [-25.41180063128769, -49.27363597352748]

CD = np.array([-25.54960180883994, -49.28392552934169])


In [3]:
CoordinatesMatrix = [HCondorTorres, SNiloPecanha, SCondorAguaVerde, HCondorNovoMundo, HCondorSãoBraz, HCondorPinheirinho, HCondorChampagnat, SCondorWenceslauBraz, HCondorSantaCandida, SCcondorMarechal, SCondorFranciscoDerosso, SCondorCampoComprido, SCondorJoãoBettega, SCondorSitioCercado, CEPostoIpiranga, SCondorBoaVista, SCondorCristoRei, SCondorAvenidaBrasilia, SCondorCajuru, SCondorSantaQuitéria, SCondorUmbará, CondorGourmetAhú, SCondorSantaFelicidade, SCondorPilarzinho, CacauShowCondorBomRetiro]

#for i in range(len(CoordinatesMatrix)):
#        CoordinatesMatrix[i] = CoordinatesMatrix[i]

CoordinatesMatrix = np.array(CoordinatesMatrix)
CoordinatesMatrix

array([[-25.48201624, -49.22050413],
       [-25.41169572, -49.27377846],
       [-25.45241153, -49.27994254],
       [-25.48587331, -49.2959319 ],
       [-25.42171285, -49.34921825],
       [-25.51547589, -49.29616495],
       [-25.43512143, -49.30378745],
       [-25.47153182, -49.26265739],
       [-25.37724549, -49.22264972],
       [-25.49219707, -49.24237339],
       [-25.51666144, -49.25626484],
       [-25.46098937, -49.34620497],
       [-25.49262512, -49.32437229],
       [-25.53401997, -49.26585745],
       [-25.43437867, -49.30937239],
       [-25.38796258, -49.24428462],
       [-25.43430692, -49.2452994 ],
       [-25.49570464, -49.27673006],
       [-25.45352051, -49.2091027 ],
       [-25.46036444, -49.32396247],
       [-25.54084242, -49.2947628 ],
       [-25.39690254, -49.25708978],
       [-25.39468014, -49.34822601],
       [-25.3885802 , -49.28295356],
       [-25.41180063, -49.27363597]])

In [4]:
def objective(x):
    X = x[0]
    Y = x[1]
    soma = 0
    for i in range(len(CoordinatesMatrix)):
        soma = soma + (X-CoordinatesMatrix[i,0])**2 + (Y-CoordinatesMatrix[i,1])**2
    return soma

In [5]:
x0 = [-25,-49]
x0 = np.array(x0)

In [73]:
sol = minimize(objective,x0,method='SLSQP')
sol

     fun: 0.09292359209717485
     jac: array([-1.19209290e-07, -8.94069672e-08])
 message: 'Optimization terminated successfully'
    nfev: 8
     nit: 2
    njev: 2
  status: 0
 success: True
       x: array([-25.45394483, -49.28020509])

In [6]:
CD

array([-25.54960181, -49.28392553])

In [78]:
def objective(x):
    X = x[0]
    Y = x[1]
    soma = 0
    for i in range(len(CoordinatesMatrix)):
        soma = soma + math.sqrt((X-CoordinatesMatrix[i,0])**2 + (Y-CoordinatesMatrix[i,1])**2)
    return soma

In [7]:
x0 = [-25,-49]
x0 = np.array(x0)

In [84]:
sol = minimize(objective,x0,method='Powell')
sol

   direc: array([[1., 0.],
       [0., 1.]])
     fun: array(1.41842465)
 message: 'Optimization terminated successfully.'
    nfev: 143
     nit: 4
  status: 0
 success: True
       x: array([-25.45243775, -49.27995549])

In [8]:
CD

array([-25.54960181, -49.28392553])